### ISSUE TITLE
I get an elem.filter is not a function error

### ISSUE THREAD

**Issue by daptordarattler** [mohamedkomalo/angular-relative-paths-in-partial#1]
Hello,

When I use this js file, I get the error: "elem.filter is not a function" and my app doesn't load. It seems angular uses jqlite, and the functions available for that does not include the filter() function. Do I need jquery to get it working?

**Comment by mohamedkomalo** [comment]
no I meant to not use jquery and use the jqlite so that it doesn't have any extra dependencies, what version of angular do you use ?

**Comment by daptordarattler** [comment]
Sorry for the late reponse, well I wasn't using jquery but angular already had jqlite so I didn't feel the need to add at to the index file. Angular v 1.34 

I eventuallt went ahead and changed the routes for all templates and ng-include to be relative to the index.html file.
Thanks

**Comment by mohamedkomalo** [comment]
I checked the the [angularjs docs](https://docs.angularjs.org/api/ng/function/angular.element) and couldn't find a "filter" function, I was working with this module in a project that had jQuery included so this is why it didn't gave me any errors. I will fix it now, thanks for the bug report
