### ISSUE TITLE
script breaks with <script type="text/ng-template" id="scriptId">

### ISSUE THREAD

**Issue by jaufgang** [mohamedkomalo/angular-relative-paths-in-partial#2]
This script is great but it generates an error in a view that contains a template of the form

&lt;script type="text/ng-template" id="scriptId"&gt;&lt;/script&gt;

This is because it is expecting the script tag to have a src attribute but it doesnt.  

The problem is easily fixed by changing 

`if (isAbsoluteUrl(elementUrl)) {return;}`

to

`if (!elementUrl || isAbsoluteUrl(elementUrl)) {    return;}`

at line 66

**Comment by mohamedkomalo** [comment]
Thanks for the bug report and the fix, much appreciated, I have modified it now.
